name: build

on:
  push:
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Display Node versions
        run: |
          node --version
          npm --version

      - name: Install dependencies
        run: npm install

      - name: Build and check generated files
        run: |
          npm run build
          script/check-generated-files

      - name: Run parse tests
        run: npm run test-parse

      - name: Run stack graph tests
        run: npm run test-stack-graphs
